x-args:
  &args
  args:
    - TZ=Europe/Berlin
    - LANG=en_US
    - VERSION_PANDOC=2.10.1
    - VERSION_ASDF=v0.10.0
    - VERSION_NODE=14.20.0
    - VERSION_RUBY=latest:2.6
    - VERSION_BUNDLER=1.17.3
x-env:
  &env
  environment:
    - CHEMOTION_GIT=https://github.com/ComPlat/chemotion_ELN.git
    - BRANCH_OR_HASH=0c606b1daf35708a0df514c0276b0ff854c021fc
    - RAILS_ENV=development
    - NODE_ENV=development
    - UID=1000
    - GID=1000
    - CHEMOTION_DIR=/chemotion
    - GEM_HOME=/chemotion/gems
    - NODE_MODULES=/chemotion/node_modules
    - YARN_CACHE=/chemotion/yarn
    - THOR_SILENCE_DEPRECATION=1
    - PGHOST=db
    - PGDATABASE=chemotion
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - WEBPACKER_DEV_SERVER_HOST=webpacker
    - WEBPACKER_DEV_SERVER_PORT=3035
    - WEBPACKER_NODE_MODULES_BIN_PATH=/chemotion/node_modules/.bin'

version: "3.5"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./cli-uuid/db:/var/lib/postgresql/data
    expose:
      - 5432

  anchor:
    <<: *env
    image: alpine/git
    volumes:
      - ./tmp:/tmp_mnt
      - ./scripts:/scripts:ro
    entrypoint: [ "/bin/sh" ]
    command: [ "/scripts/1_download_anchor.sh" ]

  hull:
    image: chemotion-dev-cli-uuid
    build:
      <<: *args
      dockerfile: scripts/2_hull.Dockerfile
    entrypoint: [ "/bin/tini", "--" ]
    command: [ "/bin/bash" ]

  sail:
    <<: *env
    image: chemotion-dev-cli-uuid
    depends_on:
      - db
    volumes:
      - ./cli-uuid/chemotion:/chemotion
      - ./scripts:/scripts:ro
      - ./tmp:/tmp_mnt
    entrypoint: [ "/bin/tini", "--" ]
    command: [ "bash", "/scripts/3_raise_sail.sh" ]

  webpacker:
    <<: *env
    image: chemotion-dev-cli-uuid
    command: [ "/chemotion/bin/webpack-dev-server" ]
    volumes:
      - ./cli-uuid/chemotion:/chemotion
    expose:
      - 3035

  ship:
    <<: *env
    image: chemotion-dev-cli-uuid
    depends_on:
      - db
      - webpacker
    volumes:
      - ./cli-uuid/chemotion:/chemotion
    working_dir: /chemotion
    command: [ "bash" ]
    tty: true
    stdin_open: true
    expose:
      - 3000
